### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by mrkvncnt** [cnguyen714/Feedr#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

Good - Let's settle on a final name by EOD. Repo should be re-titled to match.

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

looks good

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

Consider `subscribedFeeds` or something similar rather than `FeedIds` in the `Users` slice of state. 

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

`api/discover/:topic` how are topics stored on articles/feeds?

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by mrkvncnt** [comment]
Great job and nice title. See additional comments above. Any unchecked boxes should be addressed unless there is an (if needed). Great plan of action. Let's set up a 1 <> 1 to discuss your work before you get started today, just to see how you are doing.

**Comment by cnguyen714** [comment]
Regarding the foreign keys on the schema, could you clarify what the issue is?

Regarding wildcards in the API Endpoints, I have adjusted to use more descriptive wildcards like `:article_id`, or `:feed_id`

**Comment by cnguyen714** [comment]
From our discussion, we've decided that:
* the login page should be done as a modal 
* search and scoring by relevancy may be time-consuming / out-of-scope of the MVPs
* I should write my own RSS parser to populate articles from sources
* publication dates on articles should be stored, schema will be updated
* I should do some research if there is any APIs that can help seed my data
* look into having preset `:topics`, perhaps seeded from an API

**Comment by cnguyen714** [comment]
Updated backend routes to include `GET /api/feeds/:feed_id`

Otherwise, proposal is complete.
